[package]
name = "solana_network_listener"
version = "0.1.0"
edition = "2021"

[dependencies]
pcap = "0.10"
etherparse = "0.10.1"
solana-sdk = "1.8.16"
bincode = "1.3.3"
serde_json = "1.0.64"
env_logger = "0.9.0"
log = "0.4.14"
clap = "4.0"
libc = "0.2"
bs58 = "0.4"
